=== Ravinandanhv-hub/ds-b2b-manager/code-gen/flows/flow.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://appveen.com/schemas/flow.json",
  "title": "data.stack Flow",
  "description": "data.stack flow definition.",
  "type": "object",
  "properties": {
    "_id": {
      "description": "Unique flow identifier",
      "type": "string"
    },
    "name": {
      "description": "Name of the flow",
      "type": "string"
    },
    "options": {
      "type": "object",
      "properties": {
        "uniqueTxnID": {
          "type": [
            "boolean",
            "null"
          ]
        }
      }
    },
    "inputStage": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "API",
            "FILE",
            "TIMER"
          ]
        },
        "name": {
          "type": "string"
        },
        "incoming": {
          "$ref": "/schemas/incoming"
        },
        "onSuccess": {
          "$ref": "/schemas/onX"
        },
        "onError": {
          "$ref": "/schemas/onX"
        },
        "dataStructure": {
          "$ref": "/schemas/dataStructure"
        }
      },
      "required": [
        "type",
        "name",
        "incoming",
        "onSuccess",
        "dataStructure"
      ]
    },
    "stages": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {},
        "required": []
      }
    },
    "error": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {},
        "required": []
      }
    },
    "dataStructures": {}
  },
  "required": [
    "_id",
    "name",
    "inputStage",
    "stages",
    "error"
  ],
  "additionalProperties": true,
  "$defs": {
    "stage": {
      "$id": "/schemas/stage",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "API",
              "DATASERVICE",
              "FAAS",
              "TRANSFORM",
              "FOREACH",
              "REDUCE",
              "FLOW",
              "VALIDATOR",
              "AUTH-DATASTACK"
            ]
          }
        },
        "required": [
          "_id"
        ]
      }
    },
    "onX": {
      "$id": "/schemas/onX",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "condition": {
            "type": "string"
          }
        },
        "required": [
          "_id"
        ]
      }
    },
    "incoming": {
      "$id": "/schemas/incoming",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        },
        "method": {
          "type": "string",
          "enum": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "OPTIONS"
          ]
        },
        "headers": {
          "type": "object",
          "properties": {
            "Content-type": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "application/json"
                ]
              }
            }
          },
          "required": [
            "Content-Type"
          ]
        }
      },
      "required": [
        "path",
        "method",
        "headers"
      ]
    },
    "dataStructure": {
      "$id": "/schemas/dataStructure",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "properties": {
        "outgoing": {
          "type": "object",
          "properties": {
            "_id": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [
                "dataService",
                "dataFormat",
                "binary"
              ]
            }
          },
          "if": {
            "properties": {
              "type": {
                "enum": [
                  "dataService",
                  "dataFormat"
                ]
              }
            },
            "required": [
              "type"
            ]
          },
          "then": {
            "required": [
              "_id"
            ]
          },
          "else": {
            "required": []
          }
        }
      },
      "required": [
        "outgoing"
      ]
    }
  }
}

=== Ravinandanhv-hub/ds-b2b-manager/code-gen/flows/test/test.04.Branch.WithCondition.json
{
  "_id": "FLOW1001",
  "name": "Test Flow",
  "options": {
    "uniqueTxnID": true
  },
  "inputStage": {
    "type": "API",
    "name": "Get Data",
    "incoming": {
      "path": "/branchWithCondition",
      "method": "POST",
      "headers": {
        "Content-Type": [
          "application/json"
        ]
      }
    },
    "onSuccess": [
      {
        "_id": "STAGE1001"
      }
    ],
    "onError": [],
    "dataStructure": {
      "outgoing": {
        "type": "dataFormat",
        "_id": "DF1001"
      }
    }
  },
  "stages": [
    {
      "_id": "STAGE1001",
      "name": "Call external API /condition/stage1",
      "type": "API",
      "outgoing": {
        "url": "http://localhost:18080/api/condition/stage1",
        "method": "POST",
        "headers": {
          "Content-Type": "application/json"
        }
      },
      "dataStructure": {
        "outgoing": {
          "type": "dataFormat",
          "_id": "DF1001"
        }
      },
      "onSuccess": [
        {
          "_id": "STAGE1002",
          "condition": "response.data.age < 10"
        },
        {
          "_id": "STAGE1003",
          "condition": "response.data.age > 10"
        }
      ],
      "onError": []
    },
    {
      "_id": "STAGE1002",
      "name": "Call external API /condition/stage2",
      "type": "API",
      "outgoing": {
        "url": "http://localhost:18080/api/condition/stage2",
        "method": "POST",
        "headers": {
          "Content-Type": "application/json"
        }
      },
      "dataStructure": {
        "outgoing": {
          "type": "dataFormat",
          "_id": "DF1001"
        }
      },
      "onSuccess": [
        {
          "_id": "STAGE1004"
        }
      ],
      "onError": []
    },
    {
      "_id": "STAGE1003",
      "name": "Call external API /condition/stage3",
      "type": "API",
      "outgoing": {
        "url": "http://localhost:18080/api/condition/stage3",
        "method": "POST",
        "headers": {
          "Content-Type": "application/json"
        }
      },
      "dataStructure": {
        "outgoing": {
          "type": "dataFormat",
          "_id": "DF1001"
        }
      },
      "onSuccess": [
        {
          "_id": "STAGE1004"
        }
      ],
      "onError": []
    },
    {
      "_id": "STAGE1004",
      "name": "Response Node",
      "type": "RESPONSE",
      "dataStructure": {
        "outgoing": {
          "type": "dataFormat",
          "_id": "DF1001"
        }
      },
      "onSuccess": [],
      "onError": []
    }
  ],
  "error": [],
  "dataStructures": {
    "DF1001": {
      "name": "Some Structure",
      "definition": [
        {
          "key": "_id",
          "type": "String",
          "prefix": "EMP",
          "suffix": null,
          "padding": null,
          "counter": 1001,
          "properties": {
            "name": "ID",
            "required": false,
            "dataPath": "_id"
          }
        },
        {
          "type": "String",
          "key": "name",
          "properties": {
            "name": "Name",
            "dataPath": "name"
          }
        },
        {
          "type": "String",
          "key": "email",
          "properties": {
            "name": "Email",
            "dataPath": "email"
          }
        },
        {
          "type": "String",
          "key": "contactNo",
          "properties": {
            "name": "Contact No",
            "dataPath": "contactNo"
          }
        },
        {
          "type": "Number",
          "key": "age",
          "properties": {
            "name": "Age",
            "precision": 2,
            "dataPath": "age"
          }
        }
      ]
    }
  }
}

=== Ravinandanhv-hub/ds-b2b-manager/code-gen/flows/test/test.02.Mapper.json
{
  "_id": "FLOW1001",
  "name": "Test Flow",
  "options": {
    "uniqueTxnID": true
  },
  "inputStage": {
    "type": "API",
    "name": "Get Data",
    "incoming": {
      "path": "/mapper",
      "method": "POST",
      "headers": {
        "Content-Type": [
          "application/json"
        ]
      }
    },
    "onSuccess": [
      {
        "_id": "STAGE1001"
      }
    ],
    "onError": [],
    "dataStructure": {
      "outgoing": {
        "type": "dataFormat",
        "_id": "DF1001"
      }
    }
  },
  "stages": [
    {
      "_id": "STAGE1001",
      "name": "Convert from DF1001 to DF1003",
      "type": "TRANSFORM",
      "onSuccess": [
        {
          "_id": "STAGE1002"
        }
      ],
      "onError": [],
      "mapping": [
        {
          "source": [
            {
              "type": "String",
              "dataPath": "_id"
            }
          ],
          "target": {
            "type": "String",
            "dataPath": "_id"
          },
          "formula": "return input1"
        },
        {
          "source": [
            {
              "type": "String",
              "dataPath": "name"
            }
          ],
          "target": {
            "type": "String",
            "dataPath": "name"
          },
          "formula": "return input1"
        },
        {
          "source": [
            {
              "type": "String",
              "dataPath": "email"
            }
          ],
          "target": {
            "type": "String",
            "dataPath": "email"
          },
          "formula": "return input1"
        },
        {
          "source": [
            {
              "type": "Number",
              "dataPath": "contactNo"
            }
          ],
          "target": {
            "type": "Number",
            "dataPath": "contactNo"
          },
          "formula": "return input1"
        },
        {
          "source": [
            {
              "type": "Number",
              "dataPath": "age"
            }
          ],
          "target": {
            "type": "Number",
            "dataPath": "age"
          },
          "formula": "return input1"
        }
      ],
      "dataStructure": {
        "outgoing": {
          "type": "dataFormat",
          "_id": "DF1002"
        }
      }
    },
    {
      "_id": "STAGE1002",
      "name": "Call external API",
      "type": "API",
      "outgoing": {
        "url": "http://localhost:18080/api/mapper/stage2",
        "method": "POST",
        "headers": {
          "Content-Type": "application/json"
        }
      },
      "dataStructure": {
        "outgoing": {
          "type": "dataFormat",
          "_id": "DF1003"
        }
      },
      "onSuccess": [
        {
          "_id": "STAGE1003"
        }
      ],
      "onError": []
    },
    {
      "_id": "STAGE1003",
      "name": "Response Node",
      "type": "RESPONSE",
      "dataStructure": {
        "outgoing": {
          "type": "dataFormat",
          "_id": "DF1001"
        }
      },
      "onSuccess": [],
      "onError": []
    }
  ],
  "error": [],
  "dataStructures": {
    "DF1001": {
      "name": "Some Structure",
      "definition": [
        {
          "key": "_id",
          "type": "String",
          "prefix": "EMP",
          "suffix": null,
          "padding": null,
          "counter": 1001,
          "properties": {
            "name": "ID",
            "required": false,
            "dataPath": "_id"
          }
        },
        {
          "type": "String",
          "key": "name",
          "properties": {
            "name": "Name",
            "dataPath": "name"
          }
        },
        {
          "type": "String",
          "key": "email",
          "properties": {
            "name": "Email",
            "dataPath": "email"
          }
        },
        {
          "type": "String",
          "key": "contactNo",
          "properties": {
            "name": "Contact No",
            "dataPath": "contactNo"
          }
        },
        {
          "type": "Number",
          "key": "age",
          "properties": {
            "name": "Age",
            "precision": 2,
            "dataPath": "age"
          }
        }
      ]
    },
    "DF1002": {
      "name": "Some Structure",
      "definition": [
        {
          "key": "_id",
          "type": "String",
          "prefix": "EMP",
          "suffix": null,
          "padding": null,
          "counter": 1001,
          "properties": {
            "name": "ID",
            "required": false,
            "dataPath": "_id"
          }
        },
        {
          "type": "String",
          "key": "name",
          "properties": {
            "name": "Name",
            "dataPath": "name"
          }
        },
        {
          "type": "String",
          "key": "email",
          "properties": {
            "name": "Email",
            "dataPath": "email"
          }
        },
        {
          "type": "String",
          "key": "contactNo",
          "properties": {
            "name": "Contact No",
            "dataPath": "contactNo"
          }
        },
        {
          "type": "Number",
          "key": "age",
          "properties": {
            "name": "Age",
            "precision": 2,
            "dataPath": "age"
          }
        }
      ]
    },
    "DF1003": {
      "name": "Some Structure",
      "definition": [
        {
          "key": "_id",
          "type": "String",
          "prefix": "EMP",
          "suffix": null,
          "padding": null,
          "counter": 1001,
          "properties": {
            "name": "ID",
            "required": false,
            "dataPath": "_id"
          }
        },
        {
          "type": "String",
          "key": "name",
          "properties": {
            "name": "Name",
            "dataPath": "name"
          }
        },
        {
          "type": "String",
          "key": "email",
          "properties": {
            "name": "Email",
            "dataPath": "email"
          }
        },
        {
          "type": "String",
          "key": "contactNo",
          "properties": {
            "name": "Contact No",
            "dataPath": "contactNo"
          }
        },
        {
          "type": "Number",
          "key": "age",
          "properties": {
            "name": "Age",
            "precision": 2,
            "dataPath": "age"
          }
        }
      ]
    }
  }
}

=== Ravinandanhv-hub/ds-b2b-manager/code-gen/flows/test/test.99.BadJSON.MissingFields.json
{
  "_id": "FLOW1001",
  "name": "Test Flow",
  "options": {
    "uniqueTxnID": true
  },
  "inputStage": {
    "type": "API",
    "name": "Get Data",
    "incoming": {
      "method": "POST",
      "headers": {
        "Content-Type": [
          "application/json"
        ]
      }
    },
    "onSuccess": [
      {
        "_id": "STAGE1001"
      }
    ],
    "onError": [],
    "dataStructure": {
      "outgoing": {
        "type": "dataFormat",
        "_id": "DF1001"
      }
    }
  },
  "stages": [
    {
      "_id": "STAGE1001",
      "name": "Call external API 1",
      "type": "API",
      "outgoing": {
        "url": "http://localhost:18080/api/testAPI/stage1",
        "method": "POST",
        "headers": {
          "Content-Type": "application/json"
        }
      },
      "dataStructure": {
        "outgoing": {
          "type": "dataFormat",
          "_id": "DF1001"
        }
      },
      "onSuccess": [
        {
          "_id": "STAGE1002"
        }
      ],
      "onError": []
    },
    {
      "_id": "STAGE1002",
      "name": "Response node",
      "type": "RESPONSE",
      "dataStructure": {
        "outgoing": {
          "type": "dataFormat",
          "_id": "DF1001"
        }
      },
      "onSuccess": [],
      "onError": []
    }
  ],
  "error": [],
  "dataStructures": {
    "DF1001": {
      "name": "Some Structure",
      "definition": [
        {
          "key": "_id",
          "type": "String",
          "prefix": "EMP",
          "suffix": null,
          "padding": null,
          "counter": 1001,
          "properties": {
            "name": "ID",
            "required": false,
            "dataPath": "_id"
          }
        },
        {
          "type": "String",
          "key": "name",
          "properties": {
            "name": "Name",
            "dataPath": "name"
          }
        },
        {
          "type": "String",
          "key": "email",
          "properties": {
            "name": "Email",
            "dataPath": "email"
          }
        },
        {
          "type": "String",
          "key": "contactNo",
          "properties": {
            "name": "Contact No",
            "dataPath": "contactNo"
          }
        },
        {
          "type": "Number",
          "key": "age",
          "properties": {
            "name": "Age",
            "precision": 2,
            "dataPath": "age"
          }
        }
      ]
    }
  }
}
